server:
  port: 8888
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  redis:
    port: 6379
    host: localhost
xwl:
  prefix:
    url: http://localhost
    port: ${xwl.prefix.url}:5555