logging:
  level:
    com:
      itxwl: DEBUG
    org:
      springframework:
        security: DEBUG
        jdbc:
          core: TRACE
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    #url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
    url: jdbc:mysql://localhost:3306/security_test?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  h2:
    console:
      #显示 h2 嵌入式 ui 管理界面
      enabled: true
      # 访问 h2 管理界面路径
      path: /h2-console
      settings:
        # 禁止输出Trace信息
        trace: false
        # 禁止远程访问 h2 管理界面
        web-allow-others: false
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  ldap:
    base: dc=imooc,dc=com
    embedded:
      base-dn: dc=imooc,dc=com
      ldif: classpath:test-ldap-server.ldif
      port: 8388
    urls: ldap://localhost:8388/
  profiles:
    active: dev