logging:
  pattern:
    console: '%clr(%d{E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint}
              %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'
#系统环境变量
server:
  port: ${SERVER_PORT:8080}
spring:
  mail:
    host: 4
    password: 4324
    port: 43241
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: 432432
  application:
    name: uaa
  messages:
    always-use-message-format: false
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false
    #启动时初始化数据库
#  datasource:
#    initialization-mode: never
  profiles:
    active: dev
mooc:
  jwt:
    access-token-expire-time: 300000
    refresh-token-expire-tim: 2592000000
    header: Authorization
    prefix: "Bearer "
  ali:
    api-key: XXX
    api-secret: XXX
  smsProvider:
    name: ali
  lean-cloud:
    app-id: XXX
    app-key: xxx
  emailProvider:
    app-key: XXX
    name: sdasdf